// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type MemberBookStatusUpdate record {
    boolean read?;
    int? rating?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type MemberBookStatus record {
    string bookId;
    string memberId;
    boolean read;
    int? rating?;
    string updatedAt?;
};

public type NewBook record {
    string title;
    string author;
    string? isbn?;
    string? coverUrl?;
    "lookup"|"manual" 'source;
};

public type Book record {
    string id;
    string title;
    string author;
    string? isbn?;
    string? coverUrl?;
    # how the book was added
    "lookup"|"manual" 'source;
    string addedByMemberId?;
    # average of all members' ratings
    decimal? averageRating?;
    # number of members who marked it read
    int readCount?;
    string createdAt?;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type BooksPage record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Book[] data;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type BookLookupResult record {
    string title;
    string author;
    string? isbn?;
    string? coverUrl?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
